[features]
seeds = false
skip-lint = false
[programs.localnet]
token = "HmbTLCmaGvZhKnn1Zfa1JVnp7vkMV4DYVxPLWBVoN65L"
basic_token_handler = "EDR4Ycrv7rsw3B4X9e5wLmxS7g7ULbFyoY9AeCJ5ZBSn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
